name: habitat
description: A stacks used as a boilerplate for new Flutter project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dio: ^5.3.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.4
  intl: ^0.18.0
  json_annotation: ^4.8.1
  meta: ^1.10.0
  retrofit: '>=4.0.0 <5.0.0'

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.0
  mocktail: ^1.0.3
  retrofit_generator: '>=7.0.0 <8.0.0'
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
